/**
 * words.js — bundled game data.
 *
 * WORD_LIST: 2149 common four-letter English words, stored as space-separated
 * chunks (small download, trivial to diff) and expanded into a Set at load time.
 * Sources: the ENABLE open word list intersected with an OpenSubtitles frequency
 * list, filtered for profanity, slurs, proper nouns and non-English entries.
 *
 * START_WORDS: 400 curated daily starting words. Every one of them is
 * guaranteed (by breadth-first search over WORD_LIST) to have a path to
 * FISH, and to be at least 3 moves away so the puzzle is never trivial.
 *
 * Both lists are lowercase; the UI uppercases for display.
 */

const WORD_LIST_CHUNKS = [
  "abed able abut aced aces ache acid acme acne acre acts adds afar aged ages ahem ahoy aide aids",
  "ails aims airs airy ajar akin alan alas alec ales ally alma alms aloe alps also alto alum amen",
  "amid ammo amok amps ands anew anna anon ante anti ants apes apex aqua arch area ares aria arid",
  "arms army arts arty asks atom atop auld aunt aura auto avid away awed awol awry axed axel axes",
  "axis axle baba babe babu baby bach back bags bail bait bake bald bale balk ball balm band bane",
  "bang bank bans barb bard bare barf bark barn bars base bash bask bass bath bats bawl bays bead",
  "beak beam bean bear beat beau beck beds beef been beep beer bees beet begs bell belt bend bent",
  "berg berm best beta beth bets bevy bias bide bids biff bike bile bill bind bins bios bird bite",
  "bits blab blah bled blew blip blob blot blow blue blur boar boat bobs bock bode body bogs boil",
  "bold bolt bomb bond bone bong bonk bony book boom boon boor boos boot bore born bosh boss both",
  "bots bout bowl bows boyo boys bozo brad brag bran bras brat bray bred bree brew brig brim bros",
  "brow brrr bubs buck buds buff bugs bulb bulk bull bump bums bunk buns bunt buoy burg burn burp",
  "burr bury bush bust busy buts buys buzz byes cabs cafe caff cage cain cake calf call calm came",
  "camp cams cane cans cant cape caps carb card care carl carp carr cars cart casa case cash cask",
  "cast cate cats cave caws cell cent chad chap char chat chef chew chez chic chin chip chit chop",
  "chow chub chug chum ciao cite city clad clam clan clap claw clay clef clip clod clog clop clot",
  "club clue coal coat coax cobb coco code coed cogs coil coin coke cola cold cole colt coma comb",
  "come comp cone conk cons cook cool coop coos coot cope cops copy cord core cork corn cory cost",
  "cosy cots coup cove cowl cows cozy crab cram craw crew crib croc crop crow crud crux cube cubs",
  "cued cues cuff cull cult cups curb curd cure curl curt cusp cuss cute cuts cyst czar dads daft",
  "dais dale dame damp dams dang dank dare dark darn dart dash data date davy dawn days daze dead",
  "deaf deal dean dear debs debt deck deed deem deep deer deft defy deli dell demo dens dent deny",
  "desk dewy dial dibs dice died dies diet digs dike dill dime dine ding dink dips dire dirk dirt",
  "disc dish disk diss ditz diva dive dock docs dodo doer does dogs dojo dole doll dolt dome done",
  "dong dons doom door dope dork dorm dory dose doss dost dote doth dots dour dove down doze dozy",
  "drab drag dram drat draw drew drip drop drug drum dual duck duct dude duds duel dues duet duff",
  "duke dull duly dumb dump dune dung dunk dupe dusk dust duty dyed dyer dyes each earl earn ears",
  "ease east easy eats echo eddy edge edgy edit eels eggs egos elks elms else emit ends envy eons",
  "epic eras ergo euro even ever eves evil exam exec exes exit expo eyed eyes face fact fade fads",
  "fags fail fain fair fake fall fame fang fans fare farm faro fast fate fats faun faux fave fawn",
  "faze fear feat feds feed feel fees feet fell felt fend fern feta fete feud fief fife figs file",
  "fill film find fine fink fins fire firm firs fish fist fits five fizz flag flak flan flap flat",
  "flaw flax flay flea fled flee flew flex flip flit floe flog flop flow flue flux foal foam foes",
  "foil fold folk fond font food fool foot ford fore fork form fort foul four fowl foxy frat fray",
  "free fret frig frog from fuel fuji full fund funk furs fury fuse fuss fuzz gaby gaff gaga gage",
  "gags gain gait gala gale gall gals game gams gang gaps garb gash gasp gate gave gawk gays gaze",
  "gear geek geez gels gems gene gent germ gets ghee gift gigs gill gilt girl gist give glad glee",
  "glen glib glop glow glue glug glum gnat gnaw goad goal goat gobs gods goes gold golf gone gong",
  "good goof goon goop gore gory gosh gout gown grab grad gram gran gray grew grey grid grim grin",
  "grip grit grog grow grub guff gulf gull gulp gums gunk guns guru gush gust guts guys gyms gyro",
  "hack hags haha hail hair hale half hall halo halt hams hand hang hank haps hard hare hark harm",
  "harp hart hash hast hate hath hats haul have hawk hays haze hazy head heal heap hear heat heck",
  "heed heel heft heil heir held helm help hemp hens herb herd here hero hers hick hide high hike",
  "hill hilt hind hint hips hire hiss hits hive hoax hobo hock hogs hold hole holm holt holy home",
  "hone hong honk hood hoof hook hoop hoot hope hops horn hose host hots hour howe howl hows huck",
  "hues huff huge hugs hula hulk hull hump hums hung hunh hunk hunt hurl hurt hush husk huts hymn",
  "hype hypo ibis iced icky icon idea idle idly idol iffy ills imam inch info inky inns into ions",
  "iota iris iron isle itch item jabs jack jade jags jail jake jams jane jars java jaws jazz jean",
  "jeep jeez jell jerk jess jest jets jews jiff jill jinx jive jobs jock joey john join joke jolt",
  "josh joys judo juke jump junk jury just kale kane kayo keel keen keep kegs kelp kens kent kept",
  "kerb kern keys khan kick kids kill kiln kilo kilt kind king kink kins kirk kiss kite kits kiwi",
  "knee knew knit knob knot know kohl kook kris kudo labs lace lack lacy lads lady laid lain lair",
  "lake lama lamb lame lamp land lane lang laps lard lark lars lash lass last late lava lawn laws",
  "lays lazy lead leaf leak lean leap lear lech leek leer lees left legs lend lens lent less lest",
  "lets levy lewd liar lice lick lids lied lien lier lies lieu life lift like lily lima limb lime",
  "limo limp line ling link lino lint lion lips lira lire lisp list lite live load loaf loan lobe",
  "loch lock loco lode loft logo logs lone long look loom loon loop loos loot lope lord lore lose",
  "loss lost lots loud lout love lowe lows luau lube luck luge lull lulu lump luna lune lung lure",
  "lurk lush lust lute lynx lyre mace mach mack made mage magi mags maid mail maim main make mako",
  "male mall malt mama mana mane mans many maps marc mare mark mars mart mash mask mass mast mate",
  "math mats matt maul maxi maya mayo mays maze mead meal mean meat meek meet meld melt memo mend",
  "menu meow mere merl mesa mesh mess mete meth mews mica mice mick mike mild mile milk mill milo",
  "milt mime mina mind mine mini mink mint minx mire miso miss mist mite mitt moan moat mobs mock",
  "mode mods moil mojo mold mole moll moms monk mono mood moon moor moos moot mope mops mora more",
  "morn mort moss most mote moth move much muck muff mugs mule mull mums muse mush musk muss must",
  "mute mutt myth nada nags nail name nana nape naps narc nary nave navy nazi near neat neck need",
  "neon nerd ness nest nets neve news newt next nice nick nigh nine nips nite nits node nods noel",
  "noir nome none nook noon nope norm nose nosh nosy note noun nous nova nowt nuke null numb nuns",
  "nuts oaks oars oath oats obey oboe odds odor offs ogle ogre oils oily oink okay okra olds omen",
  "omer omit once ones only onto oops ooze opal open opus oral orbs orca orcs otto ouch ours outs",
  "oval oven over owed owes owls owns oxen pace pack pact pads page paid pail pain pair pale pall",
  "palm palp pals pane pang pans pant papa para pare park parr part pass past pate path pats pave",
  "pawn paws pays peak pear peas peat peck peds peed peek peel peep peer pees pegs pelt pens pent",
  "peon perk perm pert peso pest pets pews pfft phat phew pick pics pied pier pies pigs pike pile",
  "pill pimp pine ping pink pins pint pipe pips pita pits pity plan play plea pled plop plot plow",
  "ploy plug plum plus pods poem poet poke pole poll polo poly pomp pond pong pony pooh pool poop",
  "poor pope pops pore pork port pose posh post pots pour pout pows pram prat pray prep prey prim",
  "prod prof prom prop pros psst pubs puce puck puff pull pulp puma pump punk puns punt puny pups",
  "pure puri purr push puss puts putt putz pyre quad quay quid quit quiz race rack racy raff raft",
  "rage rags raid rail rain rake ramp rams rand rang rank rant raps rare rash rate rats rave rays",
  "raze read real ream reap rear redo reds reed reef reek reel rein rely rent repo reps rest revs",
  "ribs rice rich rick ride rife riff rift rigs rile rims rind ring rink riot ripe rips rise risk",
  "rite ritz road roam roan roar robe robs rock rode rods role rolf roll romp roof rook room root",
  "rope rose rosy rota rots rout roux rove rows rube rubs ruby rudd rude ruff rugs ruin rule rump",
  "rune rung runs runt ruse rush rusk rust ruth sack safe saga sage said sail sake sale salt same",
  "sand sane sang sank sans saps sari sash sass saul save saws says scab scag scam scan scar scot",
  "scow scry scud seal seam sear seas seat sect seed seek seem seen seep seer sees self sell semi",
  "send sent sera serf sets sewn shad shag shah sham shaw shay shea shed shes shim shin ship shiv",
  "shoe shoo shop shot show shun shut sick side sift sigh sign silk sill silo silt simp sims sine",
  "sing sink sins sips sire sirs site sits size skag skid skim skin skip skis skit slab slam slap",
  "slaw slay sled slew slid slim slip slit slob slog slop slot slow slug slum slur smog smug snag",
  "snap snip snit snob snog snot snow snub snug soak soap soar sobs sock soda sods sofa soft soil",
  "sold sole solo soma some song sons sook soon soot sore sort soul soup sour sown sows soya span",
  "spar spat spec sped spew spin spit spot spry spud spun spur stab stag star stat stay stem step",
  "stew stir stop stow stub stud stun subs such suds sued sues suit sulk sulu sumo sump sums sung",
  "sunk suns sure surf suss swab swag swam swan swap swat sway swig swim swum sync tabs tach tack",
  "taco tact tags tail take tale talk tall tame tang tank tans tape taps tarn taro tarp tart task",
  "tate tats taut taxi teak teal team tear teas teat teed teen tees tell temp tend tens tent term",
  "test text than that thaw thee them then they thin this thou thru thud thug thus tick tide tidy",
  "tied tier ties tiff tile till tilt time tine ting tins tint tiny tips tire titi toad toby toed",
  "toes tofu toil toke told toll tomb tome toms tone tong tons tony took tool toon toot tops tore",
  "torn toro tory toss tote tots tour tout town toys tram trap tray tree trek trey trig trim trio",
  "trip trod trot troy true tuba tube tubs tuck tuff tugs tuna tune tung turf turk turn tush tusk",
  "tutu twas twig twin twit twos tyke type typo tyre ugly ulna undo unit unto upon urge urns ursa",
  "used user uses vain vale vamp vane vans vary vase vast vats veal veer veil vein vent vera verb",
  "very vest veto vets vial vibe vice view vile vine vino visa vise vita viva void vole volt vote",
  "vows wack wade wadi wage wags waif wail wait wake walk wall wand want ward ware warm warn warp",
  "wars wart wary wash wasp wast watt wave wavy waxy ways weak wean wear webs weds weed week weep",
  "weir weld well welt went wept were west wets wham what whee when whet whew whey whim whip whir",
  "whit whiz whoa whom whys wick wide wife wigs wild wile will wilt wily wimp wind wine wing wink",
  "wino wins wipe wire wise wish wisp with wits woes woke wolf womb wont wood woof wool word wore",
  "work worm worn wort wrap wren writ yaks yams yang yank yard yarn yawn yeah year yell yelp yeti",
  "yoga yoke yolk yore your yuan yuck yule yurt zany zaps zeal zero zest zinc zing zips zits zone",
  "zoom zoos",
];

const START_WORD_CHUNKS = [
  "arms army aunt babe baby back bags bail ball band bang bank bars bath bear beat beef beep beer",
  "bell belt best bike bill bird bite blew blow boat body bond bone book boom born boss bowl boys",
  "buck bull burn busy cage cake call calm came camp card care cars cash cast cats cave cell chat",
  "chip city coat code cold cook cool cops copy cost cure cute dare dark data date dawn days deal",
  "dear deck deep deny desk dogs doll done door down drag draw drop duck dude dump dust duty earn",
  "ears ease east easy eyes face fail fair fake fall fans farm fate feed feel feet fell felt file",
  "fill film find fire firm five flag flat flew flow food fool foot four free fuel full gain game",
  "gate gave gear gift girl give glad goal gods gold golf gone good grab gray grow guys hail hair",
  "hall hand hang hard head hear heat held help hero hide hill hire hold hole holy home hood hook",
  "hope horn host hour huge hung hunt jobs join joke jump jury keep kept keys kick kids king kiss",
  "lack lady laid lake land last late lead left legs lend life lift line link lion lips live load",
  "loan lock long look lose lost lots loud love luck made maid mail make male mask mass mate math",
  "meal meat meet mile milk mind mine miss mood moon move nail name near neck need news next nine",
  "noon nose note nuts odds over owns pack page paid pair park part pass path pays pick pigs pink",
  "pipe pity play pool poor port post pour pray pull pure push race rain rare rate read rent rest",
  "rice rich ride ring rise risk road rock roll roof room rope rule rush safe sake sale salt sand",
  "save seal seat seek seen sell send sent sets shed ship shoe shop show shut side sing sink site",
  "size skip slip slow snow soft sold song sons soon soul soup spin spit spot star stay step stop",
  "suit swim tail talk tall tank tape task taxi team tear tell test text thin tied time tiny told",
  "tone took tour town trap trip tune turn vice vote wait wake walk wall warm warn wave wear week",
  "went west wide wife wild wind wine wing wipe wire woke wolf wood word wore work yard year zero",
  "zone",
];

const WORD_LIST = WORD_LIST_CHUNKS.join(" ").split(" ");
const START_WORDS = START_WORD_CHUNKS.join(" ").split(" ");

/* Exported for the Node test harness; in the browser the consts above are
   ordinary script-scope globals that script.js reads directly. */
if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORD_LIST: WORD_LIST, START_WORDS: START_WORDS };
}
