/**
 * words.js — bundled game data. Three lists, stored as space-separated chunks
 * (small download, trivial to diff) and expanded into Sets at load time.
 *
 * WORD_LIST: 3670 four-letter words the player is allowed to play — the whole
 * ENABLE open word list, minus profanity, slurs and non-English entries. It is
 * deliberately generous: a real word like CIST or FISC should never be rejected
 * as "not a word".
 *
 * COMMON_WORDS: 2144 of those that a reasonable person actually knows (ENABLE
 * intersected with an OpenSubtitles frequency list). Par is measured over this
 * subset, so the benchmark stays something a human could find. Measured over the
 * full accept list instead, par would route through obscure words and quietly
 * make every player's score look worse.
 *
 * START_WORDS: 400 curated daily starting words, all drawn from COMMON_WORDS and
 * each proven by breadth-first search to reach FISH in at least 3 moves.
 *
 * All three are lowercase; the UI uppercases for display.
 */

const WORD_LIST_CHUNKS = [
  "aahs aals abas abbe abed abet able ably abos abri abut abye abys aced aces ache achy acid acme",
  "acne acre acta acts acyl adds adit ados adze aeon aero aery afar agar agas aged agee ager ages",
  "agio agly agma agog agon ague ahem ahoy aide aids ails aims ains airn airs airt airy aits ajar",
  "ajee akee akin alae alan alar alas albs alec alee alef ales alga alif alit alky alls ally alma",
  "alme alms aloe alow alps also alto alts alum amas amen amia amid amie ammo amok amps amus amyl",
  "anas ands anes anew anga anis ankh anna anoa anon ansa anta ante anti ants aped aper apes apex",
  "apod apse aqua arak arbs arch arco arcs area ares arfs aria arid aril arks arms army arts arty",
  "arum arvo aryl asci asea ashy asks asps atap ates atma atom atop auks auld aunt aura auto aver",
  "aves avid avos avow away awed awee awes awls awns awny awol awry axal axed axel axes axil axis",
  "axle axon ayah ayes ayin azan azon baas baba babe babu baby bach back bads baff bags bail bait",
  "bake bald bale balk ball balm bals bams band bane bang bani bank bans baps barb bard bare barf",
  "bark barm barn bars base bash bask bass bast bate bath bats batt baud bawd bawl bays bead beak",
  "beam bean bear beat beau beck beds bedu beef been beep beer bees beet begs bell bels belt bema",
  "bend bens bent berg berm best beta beth bets bevy beys bhut bias bibb bibs bice bide bids bier",
  "biff bigs bike bile bilk bill bima bind bine bins bint bios bird birl birr bise bisk bite bits",
  "bitt bize blab blae blah blat blaw bleb bled blet blew blin blip blob blot blow blub blue blur",
  "boar boas boat bobs bock bode bods body boff bogs bogy boil bola bold bole boll bolt bomb bond",
  "bone bong bonk bony book boom boon boor boos boot bops bore born bort bosh bosk boss bota both",
  "bots bott bout bowl bows boxy boyo boys bozo brad brae brag bran bras brat braw bray bred bree",
  "brew brig brim brio broo bros brow brrr brut bubo bubs buck buds buff bugs buhl buhr bulb bulk",
  "bull bumf bump bums bund bunk bunn buns bunt buoy burd burg burl burn burp burr burs bury bush",
  "busk buss bust busy bute buts buys buzz byes byre byrl byte cabs cadi cads cafe caff cage cagy",
  "caid cain cake caky calf calk call calm calo calx came camp cams cane cans cant cape caph caps",
  "carb card care cark carl carn carp carr cars cart casa case cash cask cast cate cats caul cave",
  "cavy caws cays ceca cede cedi cees ceil cell cels celt cent cepe ceps cere cero cess cete chad",
  "cham chap char chat chaw chay chef chew chez chic chid chin chip chis chit chop chow chub chug",
  "chum ciao cine cion cire cist cite city clad clag clam clan clap claw clay clef clew clip clod",
  "clog clon clop clot cloy club clue coal coat coax cobb cobs coco coda code cods coed coff coft",
  "cogs coho coif coil coin coir coke cola cold cole cols colt coly coma comb come comp cone coni",
  "conk cons cony coof cook cool coop coos coot cope cops copy cord core corf cork corm corn cory",
  "cosh coss cost cosy cote cots coup cove cowl cows cowy coxa coys cozy crab crag cram craw crew",
  "crib croc crop crow crud crus crux cube cubs cuds cued cues cuff cuif cuke cull culm cult cups",
  "curb curd cure curf curl curn curr curs curt cusk cusp cuss cute cuts cwms cyan cyma cyme cyst",
  "czar dabs dace dado dads daff daft dags dahs dais daks dale dals dame damp dams dang dank daps",
  "darb dare dark darn dart dash data date daub daut davy dawk dawn daws dawt days daze dead deaf",
  "deal dean dear debs debt deck deed deem deep deer dees deet defi deft defy deil dele delf deli",
  "dell dels deme demo demy dene dens dent deny dere derm desk devs dews dewy dexy deys dhak dhal",
  "dhow dial dibs dice didy died diel dies diet digs dike dill dime dims dine ding dink dins dint",
  "diol dips dipt dire dirk dirl dirt disc dish disk diss dita dite dits ditz diva dive djin doat",
  "doby dock docs dodo doer does doff dogs dogy doit dojo dole doll dols dolt dome doms done dons",
  "doom door dopa dope dopy dore dork dorm dorp dorr dors dory dose doss dost dote doth dots doty",
  "doum dour doux dove down dows doxy doze dozy drab drag dram drat draw dray dree dreg drek drew",
  "drib drip drop drub drug drum drys duad dual dubs duci duck duct dude duds duel dues duet duff",
  "dugs duit duke dull duly dumb dump dune dung dunk duns dunt duos dupe dups dura dure durn duro",
  "durr dusk dust duty dyad dyed dyer dyes dyne each earl earn ears ease east easy eath eats eaux",
  "eave ebbs ebon eche echo ecru ecus eddo eddy edge edgy edhs edit eels eely eery effs efts egal",
  "eger eggs eggy egis egos eide eked ekes elan elds elhi elks ells elms elmy else emes emeu emfs",
  "emic emit emus emyd ends engs enol enow envy eons epee epha epic epos eras ergo ergs erne erns",
  "errs erst eses espy etas etch eths etic etna etui euro even ever eves evil ewer ewes exam exec",
  "exes exit exon expo eyas eyed eyen eyer eyes eyne eyra eyry face fact fade fads fail fain fair",
  "fake fall falx fame fang fano fans fard fare farl farm faro fash fast fate fats faun faux fava",
  "fave fawn fays faze feal fear feat feds feed feel fees feet fehs fell felt feme fems fend fens",
  "feod fere fern feta fete fets feud feus fiar fibs fice fico fids fief fife figs fila file fill",
  "film filo fils find fine fink fino fins fire firm firn firs fisc fish fist fits five fixt fizz",
  "flab flag flak flam flan flap flat flaw flax flay flea fled flee flew flex fley flic flip flit",
  "floc floe flog flop flow flub flue flus flux foal foam fobs foci foes fogs fogy fohn foil foin",
  "fold folk fond fons font food fool foot fops forb ford fore fork form fort foul four fowl foxy",
  "foys fozy frae frag frap frat fray free fret frig frit friz froe frog from frow frug fubs fuci",
  "fuds fuel fugs fuji full fume fumy fund funk funs furl furs fury fuse fuss futz fuze fuzz fyce",
  "fyke gabs gaby gadi gads gaed gaen gaes gaff gaga gage gags gain gait gala gale gall gals gamb",
  "game gamp gams gamy gane gang gaol gape gaps gapy garb gars gash gasp gast gate gats gaud gaum",
  "gaun gaur gave gawk gawp gays gaze gear geck geds geed geek geez geld gels gelt gems gene gens",
  "gent genu germ gest geta gets ghat ghee ghis gibe gibs gids gied gien gies gift giga gigs gild",
  "gill gilt gink gins gips gird girl girn girt gist gits give glad gled glee gleg glen gley glia",
  "glib glim glob glom glop glow glue glug glum glut gnar gnat gnaw gnus goad goal goas goat gobo",
  "gobs goby gods goer goes gold golf gone gong good goof goon goop goos gore gorp gory gosh gout",
  "gowd gowk gown goys grab grad gram gran grat gray gree grew grey grid grig grim grin grip grit",
  "grog grot grow grub grue grum guar guck gude guff guid gulf gull gulp guls gums gunk guns guru",
  "gush gust guts guvs guys gybe gyms gyre gyri gyro gyve haaf haar habu hack hade haed haem haen",
  "haes haet haft hags haha hahs haik hail hair hake hale half hall halm halo halt hame hams hand",
  "hang hank hant haps hard hare hark harl harm harp hart hash hasp hast hate hath hats haul haut",
  "have hawk haws hays haze hazy head heal heap hear heat heck heed heel heft hehs heil heir held",
  "helm help heme hemp hems hens hent herb herd here herl herm hern hero hers hest heth hets hewn",
  "hews hick hide hied hies high hike hila hili hill hilt hind hins hint hips hire hisn hiss hist",
  "hits hive hoar hoax hobo hobs hock hods hoed hoer hogs hold hole holk holm holp hols holt holy",
  "home homy hone hong honk hons hood hoof hook hoop hoot hope hops horn hose host hots hour hove",
  "howe howf howk howl hows hoya hoys hubs huck hued hues huff huge hugs huic hula hulk hull hump",
  "hums hung hunh hunk hunt hurl hurt hush husk huts hyla hymn hype hypo hyps hyte iamb ibex ibis",
  "iced ices ichs icky icon idea idem ides idle idly idol idyl iffy iglu ikat ikon ilea ilex ilia",
  "ilka ilks ills illy imam imid immy impi imps inby inch info inia inks inky inly inns inro inti",
  "into ions iota ired ires irid iris irks iron isba isle isms itch item iwis ixia izar jabs jack",
  "jade jagg jags jail jake jamb jams jane jape jars jato jauk jaup java jaws jays jazz jean jeed",
  "jeep jeer jees jeez jehu jell jerk jess jest jete jets jeux jews jibb jibe jibs jiff jigs jill",
  "jilt jimp jink jins jinx jive jobs jock joey jogs john join joke joky jole jolt josh jota jots",
  "jouk jowl jows joys juba jube judo juga juke jump junk jupe jury just jute juts kaas kabs kadi",
  "kaes kafs kagu kaif kail kain kaki kale kame kane kaph karn kart kats kava kayo kays kbar keas",
  "keck keef keek keel keen keep keet kefs kegs keir kelp kens kent kepi keps kept kerb kerf kern",
  "keto keys khaf khan khat khet khis kibe kick kids kief kier kifs kill kiln kilo kilt kina kind",
  "kine king kink kins kips kirk kirn kirs kiss kist kite kith kits kiva kiwi knap knar knee knew",
  "knit knop knot know knur koan koas kobs koel kohl kola kolo konk kook koph kops kore kors kris",
  "kudo kudu kues kuru kvas kyak kyar kyat kyte labs lace lack lacs lacy lade lads lady lags laic",
  "laid lain lair lake laky lall lama lamb lame lamp lams land lane lang lank laps lard lari lark",
  "lars lase lash lass last late lath lati lats laud lava lave lavs lawn laws lays laze lazy lead",
  "leaf leak leal lean leap lear leas lech leek leer lees leet left legs lehr leis leke leks leku",
  "lend lens lent lept less lest lets leud leva levo levy lewd leys liar libs lice lich lick lids",
  "lied lief lien lier lies lieu life lift like lilt lily lima limb lime limn limo limp limy line",
  "ling link lino lins lint liny lion lips lira lire liri lisp list lite lits litu live load loaf",
  "loam loan lobe lobs loch loci lock loco lode loft loge logo logs logy loll lone long loof look",
  "loom loon loop loos loot lope lops lord lore lorn lory lose loss lost lota loth loti lots loud",
  "loup lour lout love lowe lown lows luau lube luck lude lues luff luge lugs lull lulu lump lums",
  "luna lune lung lunk lunt luny lure lurk lush lust lute luvs luxe lwei lyes lynx lyre lyse maar",
  "mabe mace mach mack macs made maes mage magi mags maid mail maim main mair make mako male mall",
  "malm malt mama mana mane mans many maps marc mare mark marl mars mart mash mask mass mast mate",
  "math mats matt maul maun maut mawn maws maxi maya mayo mays maze mazy mead meal mean meat meed",
  "meek meet meld mell mels melt memo mems mend meno menu meou meow mere merk merl mesa mesh mess",
  "mete meth mewl mews meze mhos mibs mica mice midi mids mien miff migg mike mild mile milk mill",
  "milo mils milt mime mina mind mine mini mink mint minx mire mirk mirs miry mise miso miss mist",
  "mite mitt mity mixt moan moas moat mobs mock mocs mode modi mods mogs moil mojo moke mola mold",
  "mole moll mols molt mome momi moms monk mono mony mood mool moon moor moos moot mope mops mopy",
  "mora more morn mors mort mosk moss most mote moth mots moue move mown mows moxa mozo much muck",
  "muds muff mugg mugs mule mull mumm mump mums mumu muni muns muon mura mure murk murr muse mush",
  "musk muss must mute muts mutt myna myth naan nabe nabs nada nags naif nail name nana nans naoi",
  "naos nape naps narc nard nark nary nave navy nays nazi neap near neat nebs neck need neem neep",
  "neif nema neon nerd ness nest nets nett neuk neum neve nevi news newt next nibs nice nick nide",
  "nidi nigh nill nims nine nipa nips nisi nite nits nixe nixy nobs nock node nodi nods noel noes",
  "nogg nogs noil noir nolo noma nome noms none nook noon nope norm nose nosh nosy nota note noun",
  "nous nova nows nowt nubs nuke null numb nuns nurd nurl nuts oafs oaks oars oast oath oats obes",
  "obey obia obis obit oboe obol ocas odds odea odes odic odor odyl ofay offs ogam ogee ogle ogre",
  "ohed ohia ohms oils oily oink okas okay okeh okes okra olds oldy olea oleo oles olio olla omen",
  "omer omit once ones only onto onus onyx oohs oops oots ooze oozy opah opal oped open opes opts",
  "opus orad oral orbs orby orca orcs ordo ores orle orra orts oryx orzo osar oses ossa otic otto",
  "ouch ouds ouph ours oust outs ouzo oval oven over ovum owed owes owls owns owse oxen oxes oxid",
  "oxim oyer oyes paca pace pack pacs pact padi pads page paid paik pail pain pair pale pall palm",
  "palp pals paly pams pane pang pans pant papa paps para pard pare park parr pars part pase pash",
  "pass past pate path pats paty pave pawl pawn paws pays peag peak peal pean pear peas peat pech",
  "peck peds peed peek peel peen peep peer pees pegs pehs pein peke pelf pelt pend pens pent peon",
  "pepo peps perk perm pert peso pest pets pews pfft pfui phat phew phis phiz phon phot phut pial",
  "pian pias pica pice pick pics pied pier pies pigs pike piki pile pili pill pily pima pimp pine",
  "ping pink pins pint piny pion pipe pips pipy pirn piso pita pith pits pity pixy plan plat play",
  "plea pleb pled plew plie plod plop plot plow ploy plug plum plus pock pods poem poet pogy pois",
  "poke poky pole poll polo pols poly pome pomp poms pond pone pong pons pony pood pooh pool poop",
  "poor pope pops pore pork port pose posh post posy pots pouf pour pout pows pram prao prat prau",
  "pray pree prep prex prey prig prim proa prod prof prog prom prop pros prow psis psst pubs puce",
  "puck puds puff pugs pula pule puli pull pulp puls puma pump puna pung punk puns punt puny pupa",
  "pups pure puri purl purr purs push puss puts putt putz pyas pyes pyic pyin pyre qaid qats qoph",
  "quad quag quai quay quey quid quin quip quit quiz quod race rack racy rads raff raft raga rage",
  "ragi rags raia raid rail rain rake rale ramp rams rand rang rank rant raps rapt rare rase rash",
  "rasp rate rato rats rave raws rays raze razz read real ream reap rear reck recs redd rede redo",
  "reds reed reef reek reel refs reft reif rein reis rely rems rend rent repo repp reps resh rest",
  "rete rets revs rhos rhus rial rias ribs rice rich rick ride rids riel rife riff rifs rift rigs",
  "rile rill rime rims rimy rind ring rink rins riot ripe rips rise risk rite ritz rive road roam",
  "roan roar robe robs rock rocs rode rods roes roil role rolf roll romp roms rood roof rook room",
  "root rope ropy rose rosy rota rote roti rotl rots roue roup rout roux rove rows rube rubs ruby",
  "ruck rudd rude rued ruer rues ruff ruga rugs ruin rule ruly rump rums rune rung runs runt ruse",
  "rush rusk rust ruth ruts ryas ryes ryke rynd ryot sabs sack sacs sadi safe saga sage sago sags",
  "sagy said sail sain sake sale sall salp sals salt same samp sand sane sang sank sans saps sard",
  "sari sash sass sate sati saul save sawn saws says scab scad scag scam scan scar scop scot scow",
  "scry scud scup scut seal seam sear seas seat secs sect seed seek seel seem seen seep seer sees",
  "sego segs seif seis self sell sels seme semi send sene sent sera sere serf sers seta sets sett",
  "sewn sews shad shag shah sham shaw shay shea shed shes shew shim shin ship shiv shmo shod shoe",
  "shog shoo shop shot show shri shul shun shut sial sibb sibs sice sick sics side sift sigh sign",
  "sike sild silk sill silo silt simp sims sine sing sinh sink sins sipe sips sire sirs site sits",
  "size sizy skag skas skat skee skeg skep skew skid skim skin skip skis skit skua slab slam slap",
  "slat slaw slay sled slew slid slim slip slit slob sloe slog slop slot slow slub slue slug slum",
  "slur smew smit smog smug snag snap snaw sned snib snip snit snob snog snot snow snub snug snye",
  "soak soap soar sobs sock soda sods sofa soft soil soja soke sola sold sole soli solo sols soma",
  "some sone song sons sook soon soot sops sorb sord sore sori sorn sort soth sots souk soul soup",
  "sour sown sows soya soys spae span spar spat spay spec sped spew spik spin spit spiv spot spry",
  "spud spue spun spur sris stab stag star stat staw stay stem step stet stew stey stir stoa stob",
  "stop stow stub stud stum stun stye suba subs such sudd suds sued suer sues suet sugh suit sulk",
  "sulu sumo sump sums sung sunk sunn suns supe sups suqs surd sure surf suss swab swag swam swan",
  "swap swat sway swig swim swob swop swot swum sybo syce syke syli sync syph tabs tabu tace tach",
  "tack taco tact tads tael tags tahr tail tain take tala talc tale talk tall tame tamp tams tang",
  "tank tans taos tapa tape taps tare tarn taro tarp tars tart task tass tate tats taus taut tavs",
  "taws taxa taxi teak teal team tear teas teat teds teed teel teem teen tees teff tegs tela tele",
  "tell tels temp tend tens tent tepa term tern test teth tets tews text thae than that thaw thee",
  "them then thew they thin thio thir this thou thro thru thud thug thus tick tics tide tidy tied",
  "tier ties tiff tike tile till tils tilt time tine ting tins tint tiny tipi tips tire tirl tiro",
  "tivy toad toby tods tody toea toed toes toff toft tofu togs toil toit toke tola told tole toll",
  "tolu tomb tome toms tone tong tons tony took tool toom toon toot tope topi tops torc tore torn",
  "toro torr tors tort tory toss tost tote tots tour tout town tows towy toys trad tram trap tray",
  "tree tref trek tret trey trig trim trio trip trod trop trot trow troy true trug tsks tuba tube",
  "tubs tuck tufa tuff tuft tugs tuis tule tump tuna tune tung tuns tups turf turk turn tush tusk",
  "tutu twae twas twee twig twin twit twos tyee tyer tyes tyke tyne type typo typp typy tyre tyro",
  "tzar udos ughs ugly ukes ulan ulna ulus ulva umbo umps unai unau unbe unci unco unde undo undy",
  "unit unto upas upby updo upon urbs urds urea urge uric urns ursa urus used user uses utas uvea",
  "vacs vagi vain vair vale vamp vane vang vans vara vars vary vasa vase vast vats vatu vaus vavs",
  "vaws veal veep veer vees veil vein vela veld vend vent vera verb vert very vest veto vets vext",
  "vial vibe vice vide vied vier vies view viga vigs vile vims vina vine vino viny viol virl visa",
  "vise vita viva voes void vole volt vote vows vrow vugg vugh vugs wabs wack wade wadi wads wady",
  "waes waff waft wage wags waif wail wain wair wait wake wale walk wall waly wame wand wane wans",
  "want wany waps ward ware wark warm warn warp wars wart wary wash wasp wast wats watt wauk waul",
  "waur wave wavy wawl waws waxy ways weak weal wean wear webs weds weed week weel ween weep weer",
  "wees weft weir weka weld well welt wend wens went wept were wert west wets wham whap what whee",
  "when whet whew whey whid whig whim whin whip whir whit whiz whoa whom whop whys wick wide wife",
  "wigs wild wile will wilt wily wimp wind wine wing wink wino wins winy wipe wire wiry wise wish",
  "wisp wiss wist wite with wits wive woad woes woke woks wold wolf womb wonk wons wont wood woof",
  "wool woos word wore work worm worn wort wost wots wove wows wrap wren writ wych wyes wyle wynd",
  "wyns wyte xyst yack yaff yagi yaks yald yams yang yank yaps yard yare yarn yaud yaup yawl yawn",
  "yawp yaws yays yeah yean year yeas yegg yeld yelk yell yelp yens yerk yeti yett yeuk yews yill",
  "yins yips yird yirr ylem yobs yock yodh yods yoga yogh yoke yoks yolk yond yore your yowe yowl",
  "yows yuan yuca yuch yuck yuga yuks yule yups yurt ywis zags zany zaps zarf zeal zebu zeds zees",
  "zein zeks zerk zero zest zigs zill zinc zing zins zips ziti zits zoea zoic zone zonk zoom zoon",
  "zoos zori zyme",
];

const COMMON_WORD_CHUNKS = [
  "abed able abut aced aces ache acid acme acne acre acts adds afar aged ages ahem ahoy aide aids",
  "ails aims airs airy ajar akin alan alas alec ales ally alma alms aloe alps also alto alum amen",
  "amid ammo amok amps ands anew anna anon ante anti ants apes apex aqua arch area ares aria arid",
  "arms army arts arty asks atom atop auld aunt aura auto avid away awed awol awry axed axel axes",
  "axis axle baba babe babu baby bach back bags bail bait bake bald bale balk ball balm band bane",
  "bang bank bans barb bard bare barf bark barn bars base bash bask bass bath bats bawl bays bead",
  "beak beam bean bear beat beau beck beds beef been beep beer bees beet begs bell belt bend bent",
  "berg berm best beta beth bets bevy bias bide bids biff bike bile bill bind bins bios bird bite",
  "bits blab blah bled blew blip blob blot blow blue blur boar boat bobs bock bode body bogs boil",
  "bold bolt bomb bond bone bong bonk bony book boom boon boor boos boot bore born bosh boss both",
  "bots bout bowl bows boyo boys bozo brad brag bran bras brat bray bred bree brew brig brim bros",
  "brow brrr bubs buck buds buff bugs bulb bulk bull bump bums bunk buns bunt buoy burg burn burp",
  "burr bury bush bust busy buts buys buzz byes cabs cafe caff cage cain cake calf call calm came",
  "camp cams cane cans cant cape caps carb card care carl carp carr cars cart casa case cash cask",
  "cast cate cats cave caws cell cent chad chap char chat chef chew chez chic chin chip chit chop",
  "chow chub chug chum ciao cite city clad clam clan clap claw clay clef clip clod clog clop clot",
  "club clue coal coat coax cobb coco code coed cogs coil coin coke cola cold cole colt coma comb",
  "come comp cone conk cons cook cool coop coos coot cope cops copy cord core cork corn cory cost",
  "cosy cots coup cove cowl cows cozy crab cram craw crew crib croc crop crow crud crux cube cubs",
  "cued cues cuff cull cult cups curb curd cure curl curt cusp cuss cute cuts cyst czar dads daft",
  "dais dale dame damp dams dang dank dare dark darn dart dash data date davy dawn days daze dead",
  "deaf deal dean dear debs debt deck deed deem deep deer deft defy deli dell demo dens dent deny",
  "desk dewy dial dibs dice died dies diet digs dike dill dime dine ding dink dips dire dirk dirt",
  "disc dish disk diss ditz diva dive dock docs dodo doer does dogs dojo dole doll dolt dome done",
  "dons doom door dope dork dorm dory dose doss dost dote doth dots dour dove down doze dozy drab",
  "drag dram drat draw drew drip drop drug drum dual duck duct dude duds duel dues duet duff duke",
  "dull duly dumb dump dune dung dunk dupe dusk dust duty dyed dyer dyes each earl earn ears ease",
  "east easy eats echo eddy edge edgy edit eels eggs egos elks elms else emit ends envy eons epic",
  "eras ergo euro even ever eves evil exam exec exes exit expo eyed eyes face fact fade fads fail",
  "fain fair fake fall fame fang fans fare farm faro fast fate fats faun faux fave fawn faze fear",
  "feat feds feed feel fees feet fell felt fend fern feta fete feud fief fife figs file fill film",
  "find fine fink fins fire firm firs fish fist fits five fizz flag flak flan flap flat flaw flax",
  "flay flea fled flee flew flex flip flit floe flog flop flow flue flux foal foam foes foil fold",
  "folk fond font food fool foot ford fore fork form fort foul four fowl foxy frat fray free fret",
  "frig frog from fuel fuji full fund funk furs fury fuse fuss fuzz gaby gaff gaga gage gags gain",
  "gait gala gale gall gals game gams gang gaps garb gash gasp gate gave gawk gays gaze gear geek",
  "geez gels gems gene gent germ gets ghee gift gigs gill gilt girl gist give glad glee glen glib",
  "glop glow glue glug glum gnat gnaw goad goal goat gobs gods goes gold golf gone gong good goof",
  "goon goop gore gory gosh gout gown grab grad gram gran gray grew grey grid grim grin grip grit",
  "grog grow grub guff gulf gull gulp gums gunk guns guru gush gust guts guys gyms gyro hack hags",
  "haha hail hair hale half hall halo halt hams hand hang hank haps hard hare hark harm harp hart",
  "hash hast hate hath hats haul have hawk hays haze hazy head heal heap hear heat heck heed heel",
  "heft heil heir held helm help hemp hens herb herd here hero hers hick hide high hike hill hilt",
  "hind hint hips hire hiss hits hive hoax hobo hock hogs hold hole holm holt holy home hone hong",
  "honk hood hoof hook hoop hoot hope hops horn hose host hots hour howe howl hows huck hues huff",
  "huge hugs hula hulk hull hump hums hung hunh hunk hunt hurl hurt hush husk huts hymn hype hypo",
  "ibis iced icky icon idea idle idly idol iffy ills imam inch info inky inns into ions iota iris",
  "iron isle itch item jabs jack jade jags jail jake jams jane jars java jaws jazz jean jeep jeez",
  "jell jerk jess jest jets jews jiff jill jinx jive jobs jock joey john join joke jolt josh joys",
  "judo juke jump junk jury just kale kane kayo keel keen keep kegs kelp kens kent kept kerb kern",
  "keys khan kick kids kill kiln kilo kilt kind king kink kins kirk kiss kite kits kiwi knee knew",
  "knit knot know kohl kook kris kudo labs lace lack lacy lads lady laid lain lair lake lama lamb",
  "lame lamp land lane lang laps lard lark lars lash lass last late lava lawn laws lays lazy lead",
  "leaf leak lean leap lear lech leek leer lees left legs lend lens lent less lest lets levy lewd",
  "liar lice lick lids lied lien lier lies lieu life lift like lily lima limb lime limo limp line",
  "ling link lino lint lion lips lira lire lisp list lite live load loaf loan lobe loch lock loco",
  "lode loft logo logs lone long look loom loon loop loos loot lope lord lore lose loss lost lots",
  "loud lout love lowe lows luau lube luck luge lull lulu lump luna lune lung lure lurk lush lust",
  "lute lynx lyre mace mach mack made mage magi mags maid mail maim main make mako male mall malt",
  "mama mana mane mans many maps marc mare mark mars mart mash mask mass mast mate math mats matt",
  "maul maxi maya mayo mays maze mead meal mean meat meek meet meld melt memo mend menu meow mere",
  "merl mesa mesh mess mete meth mews mica mice mike mild mile milk mill milo milt mime mina mind",
  "mine mini mink mint minx mire miso miss mist mite mitt moan moat mobs mock mode mods moil mojo",
  "mold mole moll moms monk mono mood moon moor moos moot mope mops mora more morn mort moss most",
  "mote moth move much muck muff mugs mule mull mums muse mush musk muss must mute mutt myth nada",
  "nags nail name nana nape naps narc nary nave navy nazi near neat neck need neon nerd ness nest",
  "nets neve news newt next nice nick nigh nine nips nite nits node nods noel noir nome none nook",
  "noon nope norm nose nosh nosy note noun nous nova nowt nuke null numb nuns nuts oaks oars oath",
  "oats obey oboe odds odor offs ogle ogre oils oily oink okay okra olds omen omer omit once ones",
  "only onto oops ooze opal open opus oral orbs orca orcs otto ouch ours outs oval oven over owed",
  "owes owls owns oxen pace pack pact pads page paid pail pain pair pale pall palm palp pals pane",
  "pang pans pant papa para pare park parr part pass past pate path pats pave pawn paws pays peak",
  "pear peas peat peck peds peed peek peel peep peer pees pegs pelt pens pent peon perk perm pert",
  "peso pest pets pews pfft phat phew pick pics pied pier pies pigs pike pile pill pimp pine ping",
  "pink pins pint pipe pips pita pits pity plan play plea pled plop plot plow ploy plug plum plus",
  "pods poem poet poke pole poll polo poly pomp pond pong pony pooh pool poop poor pope pops pore",
  "pork port pose posh post pots pour pout pows pram prat pray prep prey prim prod prof prom prop",
  "pros psst pubs puce puck puff pull pulp puma pump punk puns punt puny pups pure puri purr push",
  "puss puts putt putz pyre quad quay quid quit quiz race rack racy raff raft rage rags raid rail",
  "rain rake ramp rams rand rang rank rant raps rare rash rate rats rave rays raze read real ream",
  "reap rear redo reds reed reef reek reel rein rely rent repo reps rest revs ribs rice rich rick",
  "ride rife riff rift rigs rile rims rind ring rink riot ripe rips rise risk rite ritz road roam",
  "roan roar robe robs rock rode rods role rolf roll romp roof rook room root rope rose rosy rota",
  "rots rout roux rove rows rube rubs ruby rudd rude ruff rugs ruin rule rump rune rung runs runt",
  "ruse rush rusk rust ruth sack safe saga sage said sail sake sale salt same sand sane sang sank",
  "sans saps sari sash sass saul save saws says scab scag scam scan scar scot scow scry scud seal",
  "seam sear seas seat sect seed seek seem seen seep seer sees self sell semi send sent sera serf",
  "sets sewn shad shag shah sham shaw shay shea shed shes shim shin ship shiv shoe shoo shop shot",
  "show shun shut sick side sift sigh sign silk sill silo silt simp sims sine sing sink sins sips",
  "sire sirs site sits size skag skid skim skin skip skis skit slab slam slap slaw slay sled slew",
  "slid slim slip slit slob slog slop slot slow slug slum slur smog smug snag snap snip snit snob",
  "snog snot snow snub snug soak soap soar sobs sock soda sods sofa soft soil sold sole solo soma",
  "some song sons sook soon soot sore sort soul soup sour sown sows soya span spar spat spec sped",
  "spew spin spit spot spry spud spun spur stab stag star stat stay stem step stew stir stop stow",
  "stub stud stun subs such suds sued sues suit sulk sulu sumo sump sums sung sunk suns sure surf",
  "suss swab swag swam swan swap swat sway swig swim swum sync tabs tach tack taco tact tags tail",
  "take tale talk tall tame tang tank tans tape taps tarn taro tarp tart task tate tats taut taxi",
  "teak teal team tear teas teat teed teen tees tell temp tend tens tent term test text than that",
  "thaw thee them then they thin this thou thru thud thug thus tick tide tidy tied tier ties tiff",
  "tile till tilt time tine ting tins tint tiny tips tire toad toby toed toes tofu toil toke told",
  "toll tomb tome toms tone tong tons tony took tool toon toot tops tore torn toro tory toss tote",
  "tots tour tout town toys tram trap tray tree trek trey trig trim trio trip trod trot troy true",
  "tuba tube tubs tuck tuff tugs tuna tune tung turf turk turn tush tusk tutu twas twig twin twit",
  "twos tyke type typo tyre ugly ulna undo unit unto upon urge urns ursa used user uses vain vale",
  "vamp vane vans vary vase vast vats veal veer veil vein vent vera verb very vest veto vets vial",
  "vibe vice view vile vine vino visa vise vita viva void vole volt vote vows wack wade wadi wage",
  "wags waif wail wait wake walk wall wand want ward ware warm warn warp wars wart wary wash wasp",
  "wast watt wave wavy waxy ways weak wean wear webs weds weed week weep weir weld well welt went",
  "wept were west wets wham what whee when whet whew whey whim whip whir whit whiz whoa whom whys",
  "wick wide wife wigs wild wile will wilt wily wimp wind wine wing wink wino wins wipe wire wise",
  "wish wisp with wits woes woke wolf womb wont wood woof wool word wore work worm worn wort wrap",
  "wren writ yaks yams yang yank yard yarn yawn yeah year yell yelp yeti yoga yoke yolk yore your",
  "yuan yuck yule yurt zany zaps zeal zero zest zinc zing zips zits zone zoom zoos",
];

const START_WORD_CHUNKS = [
  "arms army aunt babe baby back bags bail ball band bang bank bars bath bear beat beef beep beer",
  "bell belt best bike bill bird bite blew blow boat body bond bone book boom born boss bowl boys",
  "buck bull burn busy cage cake call calm came camp card care cars cash cast cats cave cell chat",
  "chip city coat code cold cook cool cops copy cost cure cute dare dark data date dawn days deal",
  "dear deck deep deny desk dogs doll done door down drag draw drop duck dude dump dust duty earn",
  "ears ease east easy eyes face fail fair fake fall fans farm fate feed feel feet fell felt file",
  "fill film find fire firm five flag flat flew flow food fool foot four free fuel full gain game",
  "gate gave gear gift girl give glad goal gods gold golf gone good grab gray grow guys hail hair",
  "hall hand hang hard head hear heat held help hero hide hill hire hold hole holy home hood hook",
  "hope horn host hour huge hung hunt jobs join joke jump jury keep kept keys kick kids king kiss",
  "lack lady laid lake land last late lead left legs lend life lift line link lion lips live load",
  "loan lock long look lose lost lots loud love luck made maid mail make male mask mass mate math",
  "meal meat meet mile milk mind mine miss mood moon move nail name near neck need news next nine",
  "noon nose note nuts odds over owns pack page paid pair park part pass path pays pick pigs pink",
  "pipe pity play pool poor port post pour pray pull pure push race rain rare rate read rent rest",
  "rice rich ride ring rise risk road rock roll roof room rope rule rush safe sake sale salt sand",
  "save seal seat seek seen sell send sent sets shed ship shoe shop show shut side sing sink site",
  "size skip slip slow snow soft sold song sons soon soul soup spin spit spot star stay step stop",
  "suit swim tail talk tall tank tape task taxi team tear tell test text thin tied time tiny told",
  "tone took tour town trap trip tune turn vice vote wait wake walk wall warm warn wave wear week",
  "went west wide wife wild wind wine wing wipe wire woke wolf wood word wore work yard year zero",
  "zone",
];

const WORD_LIST = WORD_LIST_CHUNKS.join(" ").split(" ");
const COMMON_WORDS = COMMON_WORD_CHUNKS.join(" ").split(" ");
const START_WORDS = START_WORD_CHUNKS.join(" ").split(" ");

/* Exported for the Node test harness; in the browser the consts above are
   ordinary script-scope globals that script.js reads directly. */
if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    WORD_LIST: WORD_LIST,
    COMMON_WORDS: COMMON_WORDS,
    START_WORDS: START_WORDS
  };
}
